// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bingtianyiyan/youki_gotools/commonexternal/testx/internal/config"
	"github.com/bingtianyiyan/youki_gotools/commonexternal/testx/internal/db"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.New(configConfig)
	if err != nil {
		return nil, err
	}
	dao := db.NewDao(sqlDB)
	app := NewApp(dao)
	return app, nil
}
